
spring:
  datasource:
    password: test123
    url: jdbc:mysql://localhost:3306/softeng?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
